name: Build container images

on:
  push:
    branches:
      - master
      - SOFTWARE-4832
  repository_dispatch:
    types:
      - dispatch-build
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'yongleyuan/')
    strategy:
      fail-fast: False
      matrix:
        repo: ['development', 'testing', 'release']
        registry:
          - name: OSG Harbor
            username: OSG_HARBOR_ROBOT_USER
            password: OSG_HARBOR_ROBOT_PASSWORD
          - name: Docker Hub
            username: DOCKER_USERNAME
            password: DOCKER_PASSWORD

    steps:

    - uses: actions/checkout@v2

    - name: Push container
      uses: yongleyuan/push-container-action@v1
      with:
        repo: ${{ matrix.repo }}
        registry_name: ${{ matrix.registry.name }}
        username: ${{ secrets[matrix.registry.username] }}
        password: ${{ secrets[matrix.registry.password] }}
