name: Build container images

on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - dispatch-build
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'opensciencegrid/')
    strategy:
      fail-fast: False
      matrix:
        repo: ['development', 'testing', 'release']
        registry:
          - url: hub.opensciencegrid.org
            username: OSG_HARBOR_ROBOT_USER
            password: OSG_HARBOR_ROBOT_PASSWORD
          - url: docker.io
            username: DOCKER_USERNAME
            password: DOCKER_PASSWORD

    steps:

    - uses: actions/checkout@v2

    - name: Push container
      uses: opensciencegrid/push-container-action@v1
      with:
        repo: ${{ matrix.repo }}
        registry_url: ${{ matrix.registry.url }}
        registry_user: ${{ secrets[matrix.registry.username] }}
        registry_pass: ${{ secrets[matrix.registry.password] }}
